# Generated by Django 6.0.7 on 2026-07-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('done', 'done'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.customerprofile')),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.providerservice')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleExeption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exeption', to='services.providerservice')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('saturday', 'saturday'), ('sunday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday')], max_length=40)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('provider_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='services.providerservice')),
            ],
        ),
    ]
